### ISSUE TITLE
(feature) Seatbelt system

### ISSUE THREAD

**Issue by Gellipapa** [esx-framework/esx_cruisecontrol#13]
I think we should add the seatbelt system and link it to esx_hud and everyone should be happy :)

**Comment by Gellipapa** [comment]
He does seatbelt system. (don't have dev role, he is support but thank you for your work)

![Image](https://github.com/esx-framework/esx_cruisecontrol/assets/22717950/528cc24f-eb41-47d7-b3c1-7a0d7cf4f2ce)

**Comment by Gellipapa** [comment]
If seatbelt on handle blocked leave car.

**Comment by Gellipapa** [comment]
@Rav3n95 Hi! Hi! What is the current status of the seatbelt implementation?

**Comment by Rav3n95** [comment]
Hello. I have no idea.all I did its refactoring the existing code

**Comment by SamueleAbbate** [comment]
I don't understand one thing... why do we have to integrate the belt into the cruise control and can't integrate it into the HUD?

**Comment by Gellipapa** [comment]
@SamueleAbbate Hi! That was exactly the basic plan, but then we changed it because we wanted to keep the HUD as nothing more than a data display, so the core logic won't be included because it might degrade performance. 

The reason why it's in cruisecontrol instead is exactly because that way if someone uses this script just for the belt in the future, they'll get a cruisecontrol script which is just an extra thing to add to their server and we'll handle all the stuff in the thread that's needed for a belt and a cruisecontrol script. In short, that's it.
