### ISSUE TITLE
Cruisecontrol deactivates while turn left or right

### ISSUE THREAD

**Issue by 9PaiiNz** [esx-framework/esx_cruisecontrol#22]
Hey, when i try to turn left or right the cruise control turn off.
How can i change this? Is this a bug?
It shouldnt stop while turn left or right.

**Comment by Gellipapa** [comment]
Hi! It's because when you turn the car slows down so the cruise control doesn't disengage but reduces the speed, if the cruise control is off this could be the fault. But ask the maker :) @Rav3n95

**Comment by 9PaiiNz** [comment]
Hey @Rav3n95!
Can u tell me if this is a bug or not? 
And if its not a bug, how can i change it? :D

**Comment by Rav3n95** [comment]
> 

Hello! 
Everything looks fine, make sure you are not pressing the brake or crash your vehicle.
