### ISSUE TITLE
Eject Seat don't work

### ISSUE THREAD

**Issue by Edvesse** [esx-framework/esx_cruisecontrol#27]
Hello, 

I've just tried ejecting the seat at high speed without the belt, and it doesn't work.

Could you have a look?

**Comment by Gellipapa** [comment]
@Edvesse Hi! Thanks for the report. We will test it soon and get back to you.

**Comment by Edvesse** [comment]
Hey,

Have you had time for look to the problem?

Thanks you :)

**Comment by Gellipapa** [comment]
@Edvesse I haven't had time to look at it in the last few weeks, but I'll look at it soon and reply. Until then, please be patient.

**Comment by Gellipapa** [comment]
Hi! @Edvesse  

I fixed the issue, please download the latest version and test again and report back. 

Thanks.
Fix: #29

**Comment by Edvesse** [comment]
Hello,

It's work for me, thanks you so much for your work :)
